✨ add markdown support and fix DMS type
nonebot/adapter-qqguild pull request #18
Opened 2023-01-04 16:03 UTC by KimigaiiWuyi

2023-01-05 02:32 UTC, yanyongyu commented
dms的create time不是int吗，我记得是timestamp吧

2023-01-05 02:35 UTC, KimigaiiWuyi commented
> dms的create time不是int吗，我记得是timestamp吧，或者可以直接用datetime，自动转换

昨天拿了一下，实际是str，不过不改也影响不大
[官方文档 - dms](https://bot.q.qq.com/wiki/develop/api/openapi/dms/model.html)

2023-01-05 02:36 UTC, yanyongyu commented
没关系，pydantic会根据数据自己做转换的

2023-01-05 12:53 UTC, yanyongyu requested changes

2023-01-05 12:53 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    create_time: Optional[str] = None
```suggestion
    create_time: Optional[datetime] = None
```

2023-01-05 12:53 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    guild_id: Optional[str] = None
这里没必要改吧，和api类型对应的，都是int

2023-01-06 02:52 UTC, yanyongyu approved these changes

2023-01-06 02:52 UTC, merged