:sparkles: 拆分消息发送到 bot.send_to_dms 和 bot.send_to 方法
nonebot/adapter-qqguild pull request #49
Opened 2023-08-12 20:44 UTC by Ailitonia

发送消息场景中 #3 的临时解决方法

2023-08-16 05:07 UTC, yanyongyu commented on nonebot/adapters/qqguild/bot.py
> +            **kwargs,
这里的kwargs不需要

2023-08-16 05:07 UTC, yanyongyu commented on nonebot/adapters/qqguild/bot.py
> +        **kwargs,
kwargs不需要吧

2023-08-16 16:28 UTC, Ailitonia commented
这里kwargs确实会有问题，之前有点想多了

2023-08-18 06:51 UTC, yanyongyu commented on nonebot/adapters/qqguild/bot.py
> +        guild_id: int,
这两参数顺序要不反一下？先是对象再内容

2023-08-18 06:51 UTC, yanyongyu commented on nonebot/adapters/qqguild/bot.py
> +        msg_id: Optional[int] = None,
```suggestion
        msg_id: Optional[int] = None,
```

2023-08-18 06:51 UTC, yanyongyu commented on nonebot/adapters/qqguild/bot.py
> +        channel_id: int,
这里也反一下？

2023-08-22 02:30 UTC, yanyongyu requested changes

2023-08-23 02:22 UTC, yanyongyu commented on nonebot/adapters/qqguild/bot.py
> +            guild_id=guild_id,  # type: ignore
这里为啥有个type ignore

2023-08-23 02:22 UTC, yanyongyu commented on nonebot/adapters/qqguild/bot.py
> +                guild_id=event.guild_id, message=message, msg_id=event.id
这里是不是需要type ignore，pyright过一下检查

2023-08-23 15:03 UTC, Ailitonia commented on nonebot/adapters/qqguild/bot.py
> +                guild_id=event.guild_id, message=message, msg_id=event.id
vsc用少了 没注意🤣

2023-08-25 07:36 UTC, yanyongyu approved these changes

2023-08-25 08:20 UTC, merged