feat: 添加帖子模型、事件及API
nonebot/adapter-qqguild pull request #52
Opened 2023-09-03 08:08 UTC by ssttkkl

虽然API基本是残疾（

添加API（[API定义](https://bot.q.qq.com/wiki/develop/api/openapi/forum/model.html)）：
- get_threads
- get_thread
- put_thread
- delete_thread

添加事件（[事件定义](https://bot.q.qq.com/wiki/develop/api/gateway/forum.html)）：
- ForumEvent
  - ForumThreadEvent
    - ForumThreadCreateEvent
    - ForumThreadUpdateEvent
    - ForumThreadDeleteEvent
  - ForumPostEvent
    - ForumPostCreateEvent
    - ForumPostDeleteEvent
  - ForumReplyEvent
    - ForumReplyCreateEvent
    - ForumReplyDeleteEvent
  - ForumPublishAuditResult

2023-09-03 08:16 UTC, ssttkkl commented
草，为什么PR Check还是Failed了（

2023-09-03 11:32 UTC, he0119 commented
你在本地 pre-commit install 了吗？

2023-09-04 03:33 UTC, yanyongyu requested changes

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +class RichType(int, Enum):
```suggestion
class RichType(IntEnum):
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +from enum import Enum
```suggestion
from enum import IntEnum
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    text: Optional[str]
```suggestion
    text: str
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +class AtType(int, Enum):
```suggestion
class AtType(IntEnum):
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    image = 11
```suggestion
    TEXT = 1
    AT = 2
    URL = 3
    EMOJI = 4
    CHANNEL = 5
    VIDEO = 10
    IMAGE = 11
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    at_guild = 3
```suggestion
    AT_EXPLICIT_USER = 1
    AT_ROLE_GROUP = 2
    AT_GUILD = 3
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    nick: Optional[str] = None
```suggestion
class AtUserInfo(BaseModel):
    id: int
    nick: str
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    color: Optional[int] = None
```suggestion
class AtRoleInfo(BaseModel):
    role_id: int
    name: str
    color: int
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    guild_name: Optional[str] = None
```suggestion
class AtGuildInfo(BaseModel):
    guild_id: int
    guild_name: str
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    guild_info: Optional[AtGuildInfo] = None
```suggestion
class AtInfo(BaseModel):
    type: AtType
    user_info: Optional[AtUserInfo] = None
    role_info: Optional[AtRoleInfo] = None
    guild_info: Optional[AtGuildInfo] = None
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    channel_name: Optional[str] = None
```suggestion
class ChannelInfo(BaseModel):
    channel_id: int
    channel_name: str
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    url = 4
```suggestion
class ElemType(IntEnum):
    TEXT = 1
    IMAGE = 2
    VIDEO = 3
    URL = 4
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    right = 2
```suggestion
class Alignment(IntEnum):
    LEFT = 0
    MIDDLE = 1
    RIGHT = 2
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +        if isinstance(v, str) and cls.__fields__["title"].type_ == RichText:
```suggestion
        if isinstance(v, str) and cls.__fields__["title"].type_ is RichText:
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    publish_reply = 3
```suggestion
class ForumAuditType(IntEnum):
    PUBLISH_THREAD = 1
    PUBLISH_POST = 2
    PUBLISH_REPLY = 3
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    json = 4
```suggestion
class PutThreadFormat(IntEnum):
    TEXT = 1
    HTML = 2
    MARKDOWN = 3
    JSON = 4
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    create_time: Optional[datetime] = None
```suggestion
class PutThreadReturn(BaseModel):
    task_id: int
    create_time: datetime
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    is_finish: Optional[int] = None
```suggestion
class GetThreadsReturn(BaseModel):
    threads: List[ForumThread[str]]
    is_finish: bool
```

2023-09-04 03:33 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    thread: Optional[ForumThread[str]] = None
```suggestion
class GetThreadReturn(BaseModel):
    thread: ForumThread[str]
```

2023-09-04 03:34 UTC, yanyongyu commented
enum 都用大写，有些必须有的字段不要用optional

2023-09-05 07:05 UTC, yanyongyu requested changes
看上去还是有很多字段不应该是none的

2023-09-05 07:05 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    author_id: Optional[int] = None
把不是optional的字段都改一改吧

2023-09-05 07:05 UTC, yanyongyu commented on nonebot/adapters/qqguild/event.py
> +        return str(self.author_id)
```suggestion
        return f"forum_{self.author_id}"
```

2023-09-05 12:08 UTC, ssttkkl commented
接口我又仔细测了一下，有点神必，有的时候连Elem.type都是null

以及接口文档给的一些模型我看了下没有地方用到就给删了，看文档似乎是旧版本用到的

2023-09-07 15:59 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    def infer_type(cls, values):
```suggestion
    def infer_type(cls, values: dict):
```

2023-09-07 15:59 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    type: Optional[ElemType] = None
```suggestion
    type: ElemType
```

2023-09-10 06:03 UTC, ssttkkl commented on nonebot/adapters/qqguild/api/model.py
> +    type: Optional[ElemType] = None
但是确实会收到type是空，里面所有字段都是空的Elem
```
[FORUM_THREAD_UPDATE]: {'guild_id': 134****, 'channel_id': 525****, 'author_id': 585****, 'thread_info': {'thread_id': 'B_9c5b****', 'content': {'paragraphs': [{'elems': [{'type': <ElemType.TEXT: 1>, 'text': {'text': 'test', 'props': None}, 'image': None, 'video': None, 'url': None}], 'props': {'alignment': None}}, {'elems': [{'type': None, 'text': None, 'image': None, 'video': None, 'url': None}], 'props': {'alignment': None}}, {'elems': [{'type': None, 'text': None, 'image': None, 'video': None, 'url': None}], 'props': {'alignment': None}}, {'elems': [{'type': <ElemType.TEXT: 1>, 'text': {'text': ' ', 'props': None}, 'image': None, 'video': None, 'url': None}], 'props': {'alignment': None}}]}, 'date_time': datetime.datetime(2023, 9, 10, 14, 1, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'title': {'paragraphs': [{'elems': [{'type': <ElemType.TEXT: 1>, 'text': {'text': 'test@Nomad', 'props': None}, 'image': None, 'video': None, 'url': None}], 'props': {'alignment': None}}]}}}
```
```json
{
    "guild_id": 134****,
    "channel_id": 525****,
    "author_id": 585****,
    "thread_info": {
        "thread_id": "B_9c5b****",
        "content": {
            "paragraphs": [
                {
                    "elems": [
                        {
                            "type": 1,
                            "text": {
                                "text": "test",
                                "props": null
                            },
                            "image": null,
                            "video": null,
                            "url": null
                        }
                    ],
                    "props": {
                        "alignment": null
                    }
                },
                {
                    "elems": [
                        {
                            "type": null,
                            "text": null,
                            "image": null,
                            "video": null,
                            "url": null
                        }
                    ],
                    "props": {
                        "alignment": null
                    }
                },
                {
                    "elems": [
                        {
                            "type": null,
                            "text": null,
                            "image": null,
                            "video": null,
                            "url": null
                        }
                    ],
                    "props": {
                        "alignment": null
                    }
                },
                {
                    "elems": [
                        {
                            "type": 1,
                            "text": {
                                "text": " ",
                                "props": null
                            },
                            "image": null,
                            "video": null,
                            "url": null
                        }
                    ],
                    "props": {
                        "alignment": null
                    }
                }
            ]
        },
        "date_time": "2023-09-10T14:01:00+08:00",
        "title": {
            "paragraphs": [
                {
                    "elems": [
                        {
                            "type": 1,
                            "text": {
                                "text": "test@Nomad",
                                "props": null
                            },
                            "image": null,
                            "video": null,
                            "url": null
                        }
                    ],
                    "props": {
                        "alignment": null
                    }
                }
            ]
        }
    }
}
```

2023-09-10 06:43 UTC, yanyongyu commented on nonebot/adapters/qqguild/api/model.py
> +    type: Optional[ElemType] = None
你不是在下面的validator里自动推断type了吗

2023-09-10 07:15 UTC, ssttkkl commented on nonebot/adapters/qqguild/api/model.py
> +    type: Optional[ElemType] = None
推断是给发送用的，接收遇到这种情况也推断不出来

2023-09-10 07:16 UTC, ssttkkl commented on nonebot/adapters/qqguild/api/model.py
> +    type: Optional[ElemType] = None
或者可以额外加个UNSUPPORTED的type应付这种情况

2023-09-10 07:41 UTC, yanyongyu approved these changes

2023-09-10 08:31 UTC, merged